### PR TITLE
Create update-injuries.R

### PR DESCRIPTION
**Pull request by john-b-edwards**
Relies on the NFL GSIS Data Exchange to pull weekly injury report data, historical and current. Data appears complete back to the 2009 season and only fragments are available from 2002-2008 (extensive missing weeks and teams). In the interest of completeness, 2002-2008 are omitted. Can depend on internet connection but script should take <5 minutes to complete and pull all injury reports. Creates two files in `data` when run: `nflfastR-injuries.rds` and `nflfastR-injuries.csv.gz`, both of which are fairly small relative to the other roster files.

### CODE REVIEW

**Comment by mrcaseb** [comment]
How often would you run the script @john-b-edwards? Once per day over night?

**Comment by john-b-edwards** [comment]
I imagine once per day over night in-season is fine! If you have the flexibility, I doubt you would need to update these in the off-season at all, which could save you a little bit of run-time, but it's only 5 minutes to run so the gains are probably pretty marginal.

**Comment by tanho63** [comment]
May I suggest splitting these into season-level files with something like: https://github.com/nflverse/nflfastR-roster/blob/master/R/fill_player_ids.R#L31 ?

**Comment by tanho63** [comment]
Also, perhaps could be worthwhile to only scrape data we haven't scraped before?

**Comment by john-b-edwards** [comment]
@tanho63 great call! I've added logic to do both.

**Comment by mrcaseb** [comment]
I think this is fine now. I have removed the qs files from the season level data because I think we only need the combined file as qs for nflreadr. I also pushed the data because I forgot that the new gh action would have done that for me.

**Pull request merged**
